# railway.toml - Configuración para Railway
[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
PORT = "3000"
NODE_ENV = "production"
SRI_ENVIRONMENT = "PRUEBAS"
EMISOR_RUC = "1234567890001"
EMISOR_RAZON_SOCIAL = "EMPRESA DEMO SOCIEDAD ANONIMA"
EMISOR_NOMBRE_COMERCIAL = "EMPRESA DEMO"
EMISOR_DIRECCION_MATRIZ = "Av. Principal 123 y Secundaria, Quito, Ecuador"
API_KEY = "railway_demo_api_key_2025_ecuador"
P12_BASE64 = ""
P12_PASSWORD = ""
